### ISSUE TITLE
Cannot build app with this plugin: System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.proyecto26.inappbrowser.ChromeTabsManagerActivity" not found.

### ISSUE THREAD

**Issue by aquinn637** [proyecto26/nativescript-inappbrowser#25]
I am writing an app with NativeScript 6 and Angular 8.

I am trying to use this plugin in my app.

package.json
```
{
  "nativescript": {
    "id": "org.nativescript.abc",
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "^2.2.1",
    "@schematics/angular": "^8.3.18",
    "autobind-decorator": "^2.4.0",
    "nativescript-angular": "~8.2.0",
    "nativescript-inappbrowser": "^2.2.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-dataform": "^6.0.0",
    "nativescript-unit-test-runner": "^0.7.0",
    "nativescript-urlhandler": "^1.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.1.0",
    "tns-platform-declarations": "^6.4.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "@types/jasmine": "3.4.0",
    "@types/jest": "^24.0.20",
    "@types/mocha": "^5.2.7",
    "karma": "4.4.1",
    "karma-jasmine": "2.0.1",
    "karma-nativescript-launcher": "0.4.0",
    "karma-webpack": "3.0.5",
    "nativescript-dev-webpack": "~1.2.0",
    "node-sass": "4.12.0",
    "sass": "^1.23.7",
    "sass-loader": "^8.0.0",
    "typescript": "~3.5.3"
  }
}

```

When I run **tns run android**, I get these errors:
```
System.err: An uncaught Exception occurred on "main" thread.

System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 

System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.proyecto26.inappbrowser.ChromeTabsManagerActivity" not found.

System.err:     com.tns.system.classes.loading.impl.ClassStorageServiceImpl.retrieveClass(ClassStorageServiceImpl.java:46)

System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:29)

System.err:     com.tns.Runtime.resolveClass(Runtime.java:717)

System.err:     com.tns.Runtime.runModule(Native Method)

System.err:     com.tns.Runtime.runModule(Runtime.java:662)

System.err:     com.tns.Runtime.run(Runtime.java:654)

System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)

System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)

System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:5109)

System.err:     android.app.ActivityThread.access$1600(ActivityThread.java:177)

System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)

System.err:     android.os.Handler.dispatchMessage(Handler.java:102)

System.err:     android.os.Looper.loop(Looper.java:145)

System.err:     android.app.ActivityThread.main(ActivityThread.java:5938)

System.err:     java.lang.reflect.Method.invoke(Native Method)

System.err:     java.lang.reflect.Method.invoke(Method.java:372)

System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)

System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

System.err: File: (/data/data/org.nativescript.SelfServiceApp/files/internal/ts_helpers.js:154:25)

System.err: StackTrace: 

System.err: 	(/data/data/org.nativescript.SelfServiceApp/files/internal/ts_helpers.js:154:26)

System.err: 	at DecorateConstructor(file:///node_modules\reflect-metadata\Reflect.js:541:0)

System.err: 	at decorate(file:///node_modules\reflect-metadata\Reflect.js:130:0)

System.err: 	at __decorate(/data/data/org.nativescript.SelfServiceApp/files/internal/ts_helpers.js:8:23)

System.err: 	at (file:///node_modules\nativescript-inappbrowser\ChromeTabsManagerActivity.js:80:0)

System.err: 	at (file:///node_modules\nativescript-inappbrowser\ChromeTabsManagerActivity.js:85:1)

System.err: 	at ../node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js(file:///data/data/org.nativescript.SelfServiceApp/files/app/vendor.js:92644:30)

System.err: 	at __webpack_require__(file:///src\webpack\bootstrap:750:0)

System.err: 	at fn(file:///src\webpack\bootstrap:120:0)

System.err: 	at (file:///node_modules\nativescript-inappbrowser\InAppBrowser.js:12:34)

System.err: 	at ../node_modules/nativescript-inappbrowser/InAppBrowser.js(file:///data/data/org.nativescript.SelfServiceApp/files/app/vendor.js:92929:30)

System.err: 	at __webpack_require__(file:///src\webpack\bootstrap:750:0)

System.err: 	at fn(file:///src\webpack\bootstrap:120:0)

System.err: 	at ./app/authentication/single-sign-on/sso-authentication.service.ts(file:///src\app\authentication\single-sign-on\sso-authentication.service.ts:1:0)

System.err: 	at __webpack_require__(file:///src\webpack\bootstrap:750:0)

System.err: 	at fn(file:///src\webpack\bootstrap:120:0)

System.err: 	at ./app/authentication/register-via-sso/register-via-sso.component.ts(file:///src\app\authentication\register-via-sso\register-via-sso.component.ts:1:0)

System.err: 	at __webpack_require__(file:///src\webpack\bootstrap:750:0)

System.err: 	at fn(file:///src\webpack\bootstrap:120:0)

System.err: 	at ./app/app-routing.module.ts(file:///src\app\app-routing.module.ts:1:0)

System.err: 	at __webpack_require__(file:///src\webpack\bootstrap:750:0)
```

**Comment by jdnichollsc** [comment]
Please share a repository to debug, thanks!

**Comment by slavakrampetz** [comment]
Got same issue. Test app (ns+vue blank app template), repo is here:
https://github.com/slavakrampetz/nativescript-inappbrowser-fail-example

**Comment by jdnichollsc** [comment]
let me see at night, thanks! 👍

**Comment by tobydeh** [comment]
I've got the same issue

**Comment by jdnichollsc** [comment]
Check the last version 2.3.0 and let me know 👍

**Comment by sido420** [comment]
Still having same issue with 2.3.0.

**Comment by jdnichollsc** [comment]
Try the last version 3.0.0, sorry for the delay

**Comment by jdnichollsc** [comment]
Hey folks, are you still getting this error? Please let me know!
