### ISSUE TITLE
Scoped package imports error (@nativescript/core)

### ISSUE THREAD

**Issue by uderline** [proyecto26/nativescript-inappbrowser#36]
Hi !

I upgraded to Angular 10 by following this article https://nativescript.org/blog/angular-10-support/

Even if everything works with a blank project, it seems like when adding some packages not using scoped package names, it give some errors at runtime on android and iOS (emulator).

### Log error
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10bc9c60e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10bcee5f4 -[TNSRuntime executeModule:referredBy:]
3   0x10b58ddc3 main
4   0x7fff51a231fd start
5   0x1
JavaScript stack trace:
../node_modules/nativescript-inappbrowser/InAppBrowser.js(file: node_modules/nativescript-inappbrowser/InAppBrowser.ios.js:35:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at ./app/components/welcome/welcome.component.ts(file: src/app/components/welcome/welcome.component.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at ./app/app-routing.module.ts(file: src/app/app-routing.module.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at ./app/app.module.ts(file: src/app/app.module.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at file:///app/bundle.js:3276:92
at ./main.ts(file:///app/bundle.js:3365:34)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asy<…>
JavaScript error:
file: node_modules/nativescript-inappbrowser/InAppBrowser.ios.js:35:0: JS ERROR TypeError: undefined is not an object (evaluating 'utils_1.ios.MajorVersion')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'utils_1.ios.MajorVersion')
at
../node_modules/nativescript-inappbrowser/InAppBrowser.js(file: node_modules/nativescript-inappbrowser/InAppBrowser.ios.js:35:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at ./app/components/welcome/welcome.component.ts(file: src/app/components/welcome/welcome.component.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at ./app/app-routing.module.ts(file: src/app/app-routing.module.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at ./app/app.module.ts(file: src/app/app.module.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at file:///app/bundle.js:3276:92
at ./main.ts(file:///app/bundle.js:3365:34)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpack<…>
NativeScript caught signal 6.
Native Stack:
1   0x10bced251 sig_handler(int)
2   0x7fff51c005fd _sigtramp
3   0x7fff51af4f39 itoa64
4   0x7fff51af0b7c abort
5   0x7fff4f9f7858 abort_message
6   0x7fff4f9e8cbf demangling_unexpected_handler()
7   0x7fff50ba8c0b _objc_terminate()
8   0x7fff4f9f6c87 std::__terminate(void (*)())
9   0x7fff4f9f940b __cxa_get_exception_ptr
10  0x7fff4f9f93d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x7fff50ba8ad6 _objc_exception_destructor(void*)
12  0x10bc9cb4f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x10bcee5f4 -[TNSRuntime executeModule:referredBy:]
14  0x10b58ddc3 main
15  0x7fff51a231fd start
16  0x1
```

Ok so I guessed what was important was this line: `file: node_modules/nativescript-inappbrowser/InAppBrowser.ios.js:35:0: JS ERROR TypeError: undefined is not an object (evaluating 'utils_1.ios.MajorVersion')`.

By changing (directly in the nodes_modules files) all the imports, in each file, from `tns-core-modules` to `@nativescript/core`, I managed to run my app.

I tried some changes here on my forked project and it runs: https://github.com/uderline/nativescript-inappbrowser/commit/aa9cd74b3ecbc277cb8f59fdcc1159159cdd4073

According to you, what should I do ?

Thanks,

**Comment by jdnichollsc** [comment]
Can you create a pull request to this project?

**Comment by uderline** [comment]
Sure can do !

**Comment by toby-wollit** [comment]
Any idea when you will be merging & releasing this patch?
