### ISSUE TITLE
plugin crashes app after NS7 & Angular 10 upgrade System.err: TypeError: Class constructor Observable cannot be invoked without 'new'

### ISSUE THREAD

**Issue by aquinn637** [proyecto26/nativescript-inappbrowser#39]
I have an app written with NS7 and Angular 10. Here is the sample code: https://github.com/aquinn637/NS7InAppBrowser

I am using this plugin to open a browser.

When I run the command `ns run android` I get this error:

```
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/aubrey/Documents/GitHub/NS7InAppBrowser/App_Resources/Android/app.gradle
         + using android X library androidx.legacy:legacy-support-v4:1.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/aubrey/Documents/GitHub/NS7InAppBrowser/node_modules/@nativescript/core/platforms/android/widgets-release.aar
         + adding aar plugin dependency: /Users/aubrey/Documents/GitHub/NS7InAppBrowser/node_modules/nativescript-inappbrowser/platforms/android/nativescript_inappbrowser.aar
Project successfully built.
The build result is located at: /Users/aubrey/Documents/GitHub/NS7InAppBrowser/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Installing on device 2cccaac838017ece...
Successfully installed on device with identifier '2cccaac838017ece'.
Restarting application on device 2cccaac838017ece...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Class constructor Observable cannot be invoked without 'new'
System.err: File: (file: node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js:8:0)
System.err: 
System.err: StackTrace: 
System.err: ChromeTabsEvent(file: node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js:8:0)
System.err: 	at (file: node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js:13:0)
System.err: 	at ../node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js(file:///data/data/org.nativescript.NS7InAppBrowser/files/app/vendor.js:152874:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at (file: node_modules/nativescript-inappbrowser/InAppBrowser.android.js:12:34)
System.err: 	at ../node_modules/nativescript-inappbrowser/InAppBrowser.js(file:///data/data/org.nativescript.NS7InAppBrowser/files/app/vendor.js:153115:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at ./app/item/items.component.ts(file: src/app/item/items.component.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at ./app/app-routing.module.ts(file: src/app/app-routing.module.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at ./app/app.module.ts(file: src/app/app.module.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at fn(file: src/webpack/bootstrap:120:0)
System.err: 	at (file:///data/data/org.nativescript.NS7InAppBrowser/files/app/bundle.js:305:73)
System.err: 	at ./main.ts(file:///data/data/org.nativescript.NS7InAppBrowser/files/app/bundle.js:371:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:816:0)
System.err: 	at checkDeferredModules(file: src/webpack/bootstrap:43:0)
System.err: 	at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
System.err: 	at (file:///data/data/org.nativescript.NS7InAppBrowser/files/app/bundle.js:2:57)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Class constructor Observable cannot be invoked without 'new'
```

**Comment by NathanWalker** [comment]
@proyecto26 I'll drop these references here as guides to clear that - we can try to submit a pr next week but if you want to go ahead and clear:
https://nativescript.org/blog/nativescript-7-for-plugin-authors/
and to simplify maintenance in future may want to consider:
https://nativescript.org/blog/announcing-plugin-workspaces/

**Comment by NathanWalker** [comment]
@proyecto26 I was able to get to it here: https://github.com/proyecto26/nativescript-inappbrowser/pull/40 🤗

**Comment by jdnichollsc** [comment]
Thanks Nathan for your awesome contribution! <3
