### ISSUE TITLE
Fatal Exception: android.util.SuperNotCalledException: Activity {my.app.package/com.proyecto26.inappbrowser.ChromeTabsManagerActivity} did not call through to super.onDestroy()

### ISSUE THREAD

**Issue by anmaitrannguyen** [proyecto26/nativescript-inappbrowser#42]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
This error is happen on Android 10:
```
Fatal Exception: android.util.SuperNotCalledException: Activity {my.app.package/com.proyecto26.inappbrowser.ChromeTabsManagerActivity} did not call through to super.onDestroy()
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5314)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5360)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```
I think that we have to include this line:
https://github.com/proyecto26/nativescript-inappbrowser/blob/7009e1ecc3701434509d484ac443d0b26e20e270/src/ChromeTabsManagerActivity.ts#L83
On this line, I think we have to call the super.onDestroy() on the first line (Line 66) to prevent this issues.
### Which platform(s) does your issue occur on?
- Android
- Android 10.0
- Device

**Comment by anmaitrannguyen** [comment]
https://github.com/NativeScript/NativeScript/pull/8025
Not sure this is related or not. But the fix from that pull request is for the Fragment, does we need something like that for the Activity extend?

**Comment by anmaitrannguyen** [comment]
I was able to reproduce this issues.
In my App, there a page with a button, when user tap on it, it will call the InAppBrowser function and open a link.
In some device, when the user try to tap that button 2-3 times at the same time, this crash will happen.
I'm placing some flag in my function to prevent the InAppBrowser is being called too many time now.
Will continue to check why the crash happen in this case.

**Comment by jdnichollsc** [comment]
Can you help me to debug the last changes from `develop` branch? There's a PR for the next release: https://github.com/proyecto26/nativescript-inappbrowser/pull/46

**Comment by jdnichollsc** [comment]
Please try the last version 3.0.0 👍
