### ISSUE TITLE
exception with nativescript 7

### ISSUE THREAD

**Issue by ray007** [proyecto26/nativescript-inappbrowser#44]
On upgrade to Nativescript 7, I now get an exception when trying to run my app:
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Class constructor Observable cannot be invoked without 'new'
System.err: File: (file: node_modules\nativescript-inappbrowser\ChromeTabsManagerActivity.js:8:41)
System.err:
System.err: StackTrace:
System.err: ChromeTabsEvent(file: node_modules\nativescript-inappbrowser\ChromeTabsManagerActivity.js:8:41)
System.err:     at (file: node_modules\nativescript-inappbrowser\ChromeTabsManagerActivity.js:13:34)
System.err:     at ../node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js(file:///data/data/com.my.domain/files/app/vendor.js:82059:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-inappbrowser\InAppBrowser.android.js:12:34)
System.err:     at ../node_modules/nativescript-inappbrowser/InAppBrowser.js(file:///data/data/com.my.domain/files/app/vendor.js:82371:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
```

**Comment by jdnichollsc** [comment]
Please check here https://github.com/proyecto26/nativescript-inappbrowser/pull/40#issuecomment-705674217
